name: Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Zip and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Package chrome
        run: make package-chrome
      - name: Package firefox
        run: make package-firefox
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.vars.outputs.tag }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload chrome artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gh-action-dropdown-chrome.zip
          asset_name: gh-action-dropdown-chrome.zip
          asset_content_type: application/zip
      - name: Upload firefox artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gh-action-dropdown-firefox.zip
          asset_name: gh-action-dropdown-firefox.zip
          asset_content_type: application/zip