name: Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package chrome
        run: cd chrome && zip -r -FS gh-action-dropdown-chrome.zip *
      - name: Package firefox
        run: cd firefox && zip -r -FS ../gh-action-dropdown-firefox.zip *
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload chrome artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gh-action-dropdown-chrome.zip
          asset_name: gh-action-dropdown-chrome.zip
          asset_content_type: application/zip
      - name: Upload firefox artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gh-action-dropdown-firefox.zip
          asset_name: gh-action-dropdown-firefox.zip
          asset_content_type: application/zip